### PR TITLE
Feature/plantfood

### PR DESCRIPTION
**Pull request by matthijsthoolen**
Just some simple additions to the application.

Main feature is the addition of a plant-food module (it's mainly a copy of the original plant-water feature, but in a different color)

I also expanded some readme's, mainly for development purposes. I also added a view more environment variables, especially for the firebase settings. 

Please let me know if their is anything I need to change before you can accept the pull request.

### CODE REVIEW

**Comment by morkro** [comment]
Hey @matthijsthoolen 👋 Thanks a lot for your contribution!

I really like the idea of having an additional module for fertilisation/nutritions, something I've thought about myself but wasn't sure yet how to do. Right now, the new module doesn't really differentiate from the watering module (same icon, same UX). But I am also not quite sure yet which UI would make the most sense. What are your thoughts on food/fertilisation?

As I am currently working on the new version of the app (checkout `packages/app-next`),  I don't want to spend a lot of time adding more functionality to the current version to be honest. I didn't cover plant modules yet, but will reimplement those soon. 

The watering module is being completely revamped and will get its own view and be a bigger feature in general of the new version. With that in mind, the fertilisation module could either be integrated there somehow or remain a separate module on the plant page.

Would you be willing to contribute to the new version instead?

**Comment by matthijsthoolen** [comment]
Hello @morkro 

Thank you for the feedback. I indeed did not change much for the plant-food module, mainly also because I noticed the 2.0 version. But for my own usage I really wanted a food-module, so I quickly implemented one so I could start using it :) 

I would like to help think about a better version for the 2.0 version, or some small additions to make the current version releasable for you. 

What I need for food is:
- How often do you need to give plant-food (we could go as far to make it configurable by time of the year, but I think that would be a next step)
- What plant food do you need?
- How much plant-food

I am also working on another addition to show a schedule in the app:
- When did I last water/feed the plant?
- When should I water/feed the plants again?
- An overview for all water/feed tasks for all your plants

Also thinking about some other additions like sharing the plants with your household, grouping the plants by room and adding Treffle.io 

I would like to contribute to the new version, but I am not using Vue.js often, so I don't feel I am experienced enough yet to help with 'the foundation' of the new version. I did notice the server part was build in node.js, I am more experienced with Node.js so I might be able to help a bit more with that part. 

What is your planning for the 2.0? Do you have a rough estimate on when an alpha/beta could be ready (something that equals the v1 functionality)? I noticed 1-july for v2 in the release notes, but I don't know if that is really a target or just a placeholder :)

**Comment by morkro** [comment]
Good ideas! All of what you mentioned is more or less planned for version 2 :) Happy to see that this aligns. 


>What I need for food is:
>
>How often do you need to give plant-food (we could go as far to make it configurable by time of the year, but I think that would be a next step)
>What plant food do you need?
>How much plant-food
>
>I am also working on another addition to show a schedule in the app:
>
>When did I last water/feed the plant?
>When should I water/feed the plants again?
>An overview for all water/feed tasks for all your plants

This is exactly what I am currently implementing for the new watering feature 😀 You'll have a separate screen with a calendar where you can see which plants need water. You will be able to set a schedule on the plant and define interval, notifications for reminder, etc. This could potentially be extended with fertilisation. Here's a screenshot of how this will currently look like:

Screenshot 2020-06-06 at 12 46 30

This feature is currently around 25% ready. I got the basic view implemented, now I am working on the underlying functionality.

> Also thinking about some other additions like sharing the plants with your household, grouping the plants by room and adding Treffle.io

This is on my roadmap as well.

- **Sharing household**: I am currently working out the concept and UX.
- **Grouping**: This could potentially be done via tags, but I am rethinking this approach currently as well. I was thinking about adding a general plant type (e.g. succulent, shrub, herb, ...) alongside tags.
- **Treffle.io integration**: I have followed their development for over a year now, but so far the API hasn't been very helpful. A lot of missing data, in fact I never got useful data for any plant I searched. However I saw they just released a new version with a lot of improvements. I wanted to check that out and then see if it's viable to integrate in a feature.

> I would like to contribute to the new version, but I am not using Vue.js often, so I don't feel I am experienced enough yet to help with 'the foundation' of the new version. I did notice the server part was build in node.js, I am more experienced with Node.js so I might be able to help a bit more with that part.

Nice! The long-term solution for the server is to be the middleware between Firebase and the client. I want to move most of the logic off to the server for performance reasons. Happy to have a separate chat on this.

> What is your planning for the 2.0? Do you have a rough estimate on when an alpha/beta could be ready (something that equals the v1 functionality)? I noticed 1-july for v2 in the release notes, but I don't know if that is really a target or just a placeholder :)

Once I have reimplemented existing functionality in v2 I will release it. Then I will further release more features (e.g. notifications, Treffle.io, etc) that I have planned. I think that version will be ready around early July :)

**Comment by matthijsthoolen** [comment]
The new watering view looks great! I am eagerly waiting to start using it :)

I will continue implementing some minor features in the v1 version, just to get to learn vue.js and have the features available which I want to use right now :) 

When you are a bit further in the process with the plant modules for v2, I will take a look at what I can do to help! If there is a task available for the server-side, just tag me and I will see if I can help you with that.

**Comment by morkro** [comment]
Those issues should be resolved now. The TypeScript related warnings took me a while to figure out, but I got it working now. Vue 2 with TypeScript and no class syntax is still not very smooth.

**Pull request closed without merging**
